name = "gs4-enhancive-shopper"
main = "src/index.ts"
compatibility_date = "2024-03-01"

[triggers]
crons = ["0 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "enhancive-db"
database_id = "7f60fe28-3ccd-4d23-9e70-6d6749c6c4ed"
